### ISSUE TITLE
Hint button should be inactive when there isn't a tutorial selected

### ISSUE THREAD

**Issue by henrievjen** [MissouriMRR/propguard#53]
<img width="1440" alt="Screen Shot 2020-11-05 at 5 38 39 PM" src="https://user-images.githubusercontent.com/46657460/98308482-bf951380-1f8d-11eb-9444-6cc2876f5cc0.png">

When a tutorial is not selected, clicking the Hint button currently shows the most recently visited tutorial step's hint.

If there isn't a tutorial selected, clicking the Hint button should not make the Hint Modal appear.

**Comment by tomdng** [comment]
Fixed by #68
