### ISSUE TITLE
Tutorial Editor: Step Frontend

### ISSUE THREAD

**Issue by henrievjen** [MissouriMRR/propguard#56]
Create the frontend components for the Step section of the Tutorial Editor

This section should contain three text inputs:
1) Step Title
2) Hint
3) Success message

Add grey placeholders to each search input.

![image](https://user-images.githubusercontent.com/46657460/99014520-70fcf180-2518-11eb-92ce-7d8464631065.png)

**Comment by tomdng** [comment]
Fixed with #66
