### ISSUE TITLE
Tutorial Editor: Step Content Frontend

### ISSUE THREAD

**Issue by henrievjen** [MissouriMRR/propguard#59]
Create Step Content frontend components

- Toggle between "Text" or "Code"
- Up and down arrows to move content block up or down
- Delete trash icon shows on right of content block when hovering over block
- "Add Block" button should append a content block to the bottom of the blocks

_When Text button is selected_:
- Text input should be visible
- Placeholder should read "Type text here..."

_When Code button is selected_:
- AceEditor code input should be available
- Placeholder should read "Type code here..."

![image](https://user-images.githubusercontent.com/46657460/100806757-a3528e00-33f6-11eb-8459-64c6398b2cb3.png)

**Comment by tomdng** [comment]
Fixed with #66
